# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-07-15T21:49:45+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Annotated, Any
from uuid import UUID

from pydantic import BaseModel, Field, RootModel


class StorytellerName(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1)]


class Status(Enum):
    ok = 'ok'
    degraded = 'degraded'


class HealthResponse(BaseModel):
    status: Annotated[Status, Field(examples=['ok'])]
    db_connected: Annotated[bool, Field(examples=[True])]


class GameImportStatusResponse(BaseModel):
    status: Annotated[str, Field(examples=['ok'])]
    game_id: Annotated[str | None, Field(examples=['42'])] = None
    players_created: Annotated[int, Field(examples=[5])]
    errors: list[str]


class GamesImportStatusResponse(BaseModel):
    games: Annotated[list[GameImportStatusResponse] | None, Field(min_length=1)] = None


class RolesImportResponse(BaseModel):
    status: Annotated[str, Field(examples=['ok'])]
    roles_created: Annotated[int, Field(examples=[3])]
    roles_updated: Annotated[int, Field(examples=[1])]
    errors: list[str]


class RoleTranslation(BaseModel):
    name: Annotated[str, Field(examples=['Дамочка'], max_length=200, min_length=1)]
    description: Annotated[
        str | None,
        Field(examples=['Служанка, которая следит за гостями'], max_length=2000),
    ] = None


class ErrorResponse(BaseModel):
    detail: str | dict[str, Any]


class PlayerImportRequest(BaseModel):
    name: Annotated[
        str, Field(examples=['Мая Вишневская'], max_length=200, min_length=1)
    ]
    seat_number: Annotated[int | None, Field(examples=[1], ge=1)] = None
    role_start: Annotated[
        str, Field(examples=['Дамочка'], max_length=200, min_length=1)
    ]
    role_end: Annotated[str, Field(examples=['Дамочка'], max_length=200, min_length=1)]
    alignment_end: Annotated[
        str, Field(examples=['добро'], pattern='^(добро|зло|нейтральный)$')
    ]
    is_alive: Annotated[bool, Field(examples=[True])]


class PlayerItem(BaseModel):
    id: Annotated[UUID, Field(examples=['b1c2d3e4-f5a6-7890-abcd-1234567890ef'])]
    name: Annotated[str, Field(examples=['Alice'])]


class GameImportRequest(BaseModel):
    game_date: Annotated[date, Field(examples=['2026-01-15'])]
    scenario_name: Annotated[
        str, Field(examples=['Вселенная зла'], max_length=300, min_length=1)
    ]
    storyteller_names: Annotated[
        list[StorytellerName],
        Field(
            description='Names of the storyteller(s) running this game (more than one for co-storytelling).',
            examples=[['МелонКО']],
            max_length=5,
            min_length=1,
        ),
    ]
    alignment_win: Annotated[
        str, Field(examples=['добро'], pattern='^(добро|зло|ничья)$')
    ]
    location: Annotated[
        str,
        Field(examples=['Москва, Антикафе на Арбате'], max_length=300, min_length=1),
    ]
    game_number: Annotated[int, Field(examples=[1], ge=1)]
    duration: Annotated[str | None, Field(examples=['01:30:00'])] = None
    notes: Annotated[
        str | None,
        Field(examples=['Отличная партия, все получили удовольствие'], max_length=2000),
    ] = None
    players: Annotated[list[PlayerImportRequest], Field(max_length=30, min_length=1)]


class GamesImportRequest(BaseModel):
    games: Annotated[list[GameImportRequest], Field(min_length=1)]


class RoleImportItem(BaseModel):
    name: Annotated[str, Field(examples=['Chambermaid'], max_length=200, min_length=1)]
    alignment: Annotated[str, Field(examples=['good'], pattern='^(good|evil|neutral)$')]
    role_type: Annotated[
        str,
        Field(
            examples=['Outsider'],
            pattern='^(Townsfolk|Outsider|Minion|Demon|Traveller)$',
        ),
    ]
    description: Annotated[
        str | None, Field(examples=['Simple, but not harmless'], max_length=2000)
    ] = None
    translations: Annotated[
        dict[str, RoleTranslation] | None,
        Field(
            examples=[
                {
                    'ru': {
                        'name': 'Дамочка',
                        'description': 'Служанка, которая следит за гостями',
                    }
                }
            ]
        ),
    ] = None


class RolesImportRequest(BaseModel):
    roles: Annotated[list[RoleImportItem], Field(max_length=200, min_length=1)]


class PlayersResponse(BaseModel):
    players: list[PlayerItem]


class RoleItem(BaseModel):
    id: Annotated[UUID, Field(examples=['a09f3ff7-0f02-485a-b0e1-87388b27face'])]
    name: Annotated[str, Field(examples=['Chambermaid'])]
    alignment: Annotated[str, Field(examples=['good'], pattern='^(good|evil|neutral)$')]
    role_type: Annotated[
        str,
        Field(
            examples=['Outsider'],
            pattern='^(Townsfolk|Outsider|Minion|Demon|Traveller)$',
        ),
    ]
    description: Annotated[str | None, Field(examples=['Simple, but not harmless'])] = (
        None
    )
    translation: Annotated[
        RoleTranslation | None,
        Field(
            description='Translation into the requested language (only present when the lang query parameter was provided).'
        ),
    ] = None


class RolesResponse(BaseModel):
    roles: list[RoleItem]
