# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-05-17T17:32:55+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, Field


class PlayerImportRequest(BaseModel):
    name: Annotated[
        str, Field(examples=['Мая Вишневская'], max_length=200, min_length=1)
    ]
    seat_number: Annotated[int | None, Field(examples=[1], ge=1)] = None
    role_start: Annotated[
        str, Field(examples=['Дамочка'], max_length=200, min_length=1)
    ]
    role_end: Annotated[str, Field(examples=['Дамочка'], max_length=200, min_length=1)]
    alignment_end: Annotated[
        str, Field(examples=['добро'], pattern='^(добро|зло|нейтральный)$')
    ]
    is_alive: Annotated[bool, Field(examples=[True])]


class Player(BaseModel):
    name: Annotated[
        str, Field(examples=['Мая Вишневская'], max_length=200, min_length=1)
    ]
    seat_number: Annotated[int | None, Field(examples=[1], ge=1)] = None
    role_start: Annotated[
        str, Field(examples=['Дамочка'], max_length=200, min_length=1)
    ]
    role_end: Annotated[str, Field(examples=['Дамочка'], max_length=200, min_length=1)]
    alignment_end: Annotated[
        str, Field(examples=['добро'], pattern='^(добро|зло|нейтральный)$')
    ]
    is_alive: Annotated[bool, Field(examples=[True])]


class GameImportRequest(BaseModel):
    game_date: Annotated[date, Field(examples=['2026-01-15'])]
    scenario_name: Annotated[
        str, Field(examples=['Вселенная зла'], max_length=300, min_length=1)
    ]
    storyteller_name: Annotated[
        str, Field(examples=['МелонКО'], max_length=200, min_length=1)
    ]
    alignment_win: Annotated[str, Field(examples=['добро'], pattern='^(добро|зло)$')]
    location: Annotated[
        str,
        Field(examples=['Москва, Антикафе на Арбате'], max_length=300, min_length=1),
    ]
    game_number: Annotated[int, Field(examples=[1], ge=1)]
    duration: Annotated[str | None, Field(examples=['01:30:00'])] = None
    notes: Annotated[
        str | None,
        Field(examples=['Отличная партия, все получили удовольствие'], max_length=2000),
    ] = None
    players: Annotated[list[Player], Field(max_length=30, min_length=1)]


class Translations(BaseModel):
    name: Annotated[str, Field(examples=['Дамочка'], max_length=200, min_length=1)]
    description: Annotated[
        str | None,
        Field(examples=['Служанка, которая следит за гостями'], max_length=2000),
    ] = None


class RoleImportItem(BaseModel):
    name: Annotated[str, Field(examples=['Chambermaid'], max_length=200, min_length=1)]
    alignment: Annotated[str, Field(examples=['good'], pattern='^(good|evil|neutral)$')]
    role_type: Annotated[
        str,
        Field(
            examples=['Outsider'],
            pattern='^(Townsfolk|Outsider|Minion|Demon|Traveller)$',
        ),
    ]
    description: Annotated[
        str | None, Field(examples=['Simple, but not harmless'], max_length=2000)
    ] = None
    translations: Annotated[
        dict[str, Translations] | None,
        Field(
            examples=[
                {
                    'ru': {
                        'name': 'Дамочка',
                        'description': 'Служанка, которая следит за гостями',
                    }
                }
            ]
        ),
    ] = None


class Role(BaseModel):
    name: Annotated[str, Field(examples=['Chambermaid'], max_length=200, min_length=1)]
    alignment: Annotated[str, Field(examples=['good'], pattern='^(good|evil|neutral)$')]
    role_type: Annotated[
        str,
        Field(
            examples=['Outsider'],
            pattern='^(Townsfolk|Outsider|Minion|Demon|Traveller)$',
        ),
    ]
    description: Annotated[
        str | None, Field(examples=['Simple, but not harmless'], max_length=2000)
    ] = None
    translations: Annotated[
        dict[str, Translations] | None,
        Field(
            examples=[
                {
                    'ru': {
                        'name': 'Дамочка',
                        'description': 'Служанка, которая следит за гостями',
                    }
                }
            ]
        ),
    ] = None


class RolesImportRequest(BaseModel):
    roles: Annotated[list[Role], Field(max_length=200, min_length=1)]


class Status(Enum):
    ok = 'ok'
    degraded = 'degraded'


class HealthResponse(BaseModel):
    status: Annotated[Status, Field(examples=['ok'])]
    db_connected: Annotated[bool, Field(examples=[True])]


class ImportStatusResponse(BaseModel):
    status: Annotated[str, Field(examples=['ok'])]
    game_id: Annotated[str | None, Field(examples=['42'])] = None
    players_created: Annotated[int, Field(examples=[5])]
    errors: list[str]


class Translation(BaseModel):
    name: Annotated[str, Field(examples=['Дамочка'], max_length=200, min_length=1)]
    description: Annotated[
        str | None,
        Field(examples=['Служанка, которая следит за гостями'], max_length=2000),
    ] = None


class Role1(BaseModel):
    id: Annotated[int, Field(examples=[1])]
    name: Annotated[str, Field(examples=['Chambermaid'])]
    alignment: Annotated[str, Field(examples=['good'], pattern='^(good|evil|neutral)$')]
    role_type: Annotated[
        str,
        Field(
            examples=['Outsider'],
            pattern='^(Townsfolk|Outsider|Minion|Demon|Traveller)$',
        ),
    ]
    description: Annotated[str | None, Field(examples=['Simple, but not harmless'])] = (
        None
    )
    translation: Annotated[
        Translation | None,
        Field(
            description='Перевод на запрошенный язык (если был указан параметр lang).'
        ),
    ] = None


class RolesResponse(BaseModel):
    roles: list[Role1]


class RolesImportResponse(BaseModel):
    status: Annotated[str, Field(examples=['ok'])]
    roles_created: Annotated[int, Field(examples=[3])]
    roles_updated: Annotated[int, Field(examples=[1])]
    errors: list[str]


class RoleItem(BaseModel):
    id: Annotated[int, Field(examples=[1])]
    name: Annotated[str, Field(examples=['Chambermaid'])]
    alignment: Annotated[str, Field(examples=['good'], pattern='^(good|evil|neutral)$')]
    role_type: Annotated[
        str,
        Field(
            examples=['Outsider'],
            pattern='^(Townsfolk|Outsider|Minion|Demon|Traveller)$',
        ),
    ]
    description: Annotated[str | None, Field(examples=['Simple, but not harmless'])] = (
        None
    )
    translation: Annotated[
        Translation | None,
        Field(
            description='Перевод на запрошенный язык (если был указан параметр lang).'
        ),
    ] = None


class RoleTranslation(BaseModel):
    name: Annotated[str, Field(examples=['Дамочка'], max_length=200, min_length=1)]
    description: Annotated[
        str | None,
        Field(examples=['Служанка, которая следит за гостями'], max_length=2000),
    ] = None


class ErrorResponse(BaseModel):
    detail: str | dict[str, Any]
